name: release

on: [push, pull_request, release]

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
        - uses: actions/checkout@v2
        - name: prepare docker
          run: |
            mkdir -p $HOME/.docker
            echo '{ "experimental": "enabled" }' | tee $HOME/.docker/config.json
            echo '{ "experimental": true, "storage-driver": "overlay2", "max-concurrent-downloads": 50, "max-concurrent-uploads": 50 }' | sudo tee /etc/docker/daemon.json
            sudo systemctl restart docker
            docker buildx create --use --name mybuild
        - name: build
          run: make cross_build
        - uses: actions/upload-artifact@v1
          with:
            name: packages
            path: _packages/.

    build-on-mac:
        runs-on: macos-latest

        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-go@v1
          with:
            go-version: '1.11.5'
        - name: prepare
          run: |
              /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
              brew install curl zip unzip gnu-sed upx
              echo "/usr/local/bin:$PATH" >> ~/.bashrc
        - name: build
          run: make pkg
        - uses: actions/upload-artifact@v1
          with:
            name: packages-mac
            path: _packages/.
        