name: Run all test cases

on: [push, pull_request, release]

jobs:
    run_test_case:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-go@v1
          with:
            go-version: '1.11.5' # The Go version to download (if necessary) and use.
        - name: run test case
          run: go test ./...
    